In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import scipy as sp
from scipy.optimize import leastsq

def GM_11_pretest(data):
    ago_sequence = np.cumsum(data)
    smooth_ratios = ago_sequence[1:] / ago_sequence[:-1]
    smooth_ratios = smooth_ratios[1:]
    satisfying_ratios = (smooth_ratios >= 1) & (smooth_ratios <= 1.5)
    satisfying_ratio_percentage = np.sum(satisfying_ratios) / len(satisfying_ratios)
    return satisfying_ratio_percentage

def GM_11_minfunc(params, B, Y):
    x0, b = params
    return B.dot(params) - Y

def GM_11_fit(data):
    X1 = data.cumsum()
    X1 = (X1[:-1]+X1[1:])/2.0
    B = np.vstack((-X1, np.ones(len(X1)))).T
    Y = data[1:]
    p, pcov = leastsq(GM_11_minfunc, [1, 1], args=(B, Y))
    return p

def GM_11_sum_predicate(x0, a, b, x):
    if(x < 0):
        return 0
    return (x0 - b / a) * np.exp(-a * x) + b / a

def GM_11_predicate(x0, a, b, x):
    return GM_11_sum_predicate(x0, a, b, x) - GM_11_sum_predicate(x0, a, b, x - 1)

def GM_11_posttest(data, p):#均方差比，平均相对误差
    a, b = p
    x0 = data[0]
    x_pred = np.array([GM_11_predicate(x0, a, b, i) for i in range(len(data))])
    e = data - x_pred
    S1 = np.array(data).var()
    S2 = np.array(e).var()
    MSER = S2 / S1
    MRE = np.abs(e / data).mean()
    return MSER, MRE

In [21]:
data = pd.read_csv('LBMA-GOLD.csv')
data['DayFromBegin'] = pd.to_datetime(data['Date'],format='%m/%d/%y').map(lambda x: (x - pd.to_datetime('2016-9-11')).days)
data['RowNumber'] = range(0, len(data))

         Date  USD (PM)  DayFromBegin  RowNumber
0     9/12/16   1324.60             1          0
1     9/13/16   1323.65             2          1
2     9/14/16   1321.75             3          2
3     9/15/16   1310.80             4          3
4     9/16/16   1308.35             5          4
...       ...       ...           ...        ...
1260   9/6/21   1821.60          1821       1260
1261   9/7/21   1802.15          1822       1261
1262   9/8/21   1786.00          1823       1262
1263   9/9/21   1788.25          1824       1263
1264  9/10/21   1794.60          1825       1264

[1265 rows x 4 columns]

In [ ]:
# 灰色预测
start = 1
length = 20
duration = 10